### ISSUE TITLE
Table view: Bullet and cursor overlay are positioned incorrectly

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1498] opened 2022-01-29 14:03 UTC
There are three different cursor locations where the bullet or cursor is positioned incorrectly. 

## Steps to Reproduce

```
- a
  - =view
    - Table
  - b
    - b1
    - b2
  - d
    - d1
    - d2
```

Change the in-app font size to 24. You can adjust the font size by clicking the large `A` link in the footer.  

## Current Behavior

1. Column 1 bullet with cursor is not vertically centered with its corresponding thought, `b`. 

![image](https://user-images.githubusercontent.com/750276/151663930-4003feb8-72a8-4ccd-b175-48f8f12576f6.jpeg)

2. The cursor overlay bullet in the first thought in column 2 is not centered over the bullet. 

![image](https://user-images.githubusercontent.com/750276/151663956-45f2680a-a7e6-4436-b0a3-8aab35ceb554.jpeg)

3. The cursor overlay bullet in the second thought in column 2 is not centered over the bullet.

![image](https://user-images.githubusercontent.com/750276/151663972-248fce54-666e-4c22-8eff-505bf546f878.jpeg)

## Expected Behavior

Bullet and cursor overlay bullet should be positioned correctly.

## Notes
 
The solution should work on all in-app font sizes on both Chrome and Safari.

**Comment by nepali-prabhat** [comment] 2022-01-30 10:32
@raineorshine 
We are using `position: "absolute"` for bullet cursor overlay. We could've also added a div below each bullets and toggled its css class. The current approach has a lot of overhead and inconsistencies. 
Is there some performance optimization we are getting from the current approach?

**Comment by raineorshine** [comment] 2022-01-30 14:11
Could you explain the two approaches in more detail, the existing one, your suggestion, and how exactly they differ? That would help me better evaluate the suggestion.

**Comment by nepali-prabhat** [comment] 2022-01-31 02:28
## The current scenario
The cursor overlay is being rendered from the `BulletCursorOverlay` component. The component renders a span with `position: absolute`. We are then manipulating the properties `top`, `left`, etc to position the cursor overlay below bullet.

## The problem
Manually setting the position properties has the following caveats:
1. The css rules are extremely difficult to keep track. There are about 61 references of `.bullet-cursor-overlay` in `App.css` most of which involve rules setting top, left, margin, etc.
2. There arise several inconsistencies with style. We are having to write css rule for each case involving inconsistency.

## Proposed solution 1
1. Instead of putting the cursor overlay in StaticThought component, add a new element in the Bullet component itself (like in code example below)
2. Style the element as cursor overlay and position it below glyph. (This is comparatively easier task because we are essentially positioning 2 sibblings on top of each other. Moreover, we won't have those massive jumps in positioning.)
3. The new element initially has `color: transparent` style
4. If the element is inside thought that is being edited, set `color: rgba(255, 255, 255, 0.25)`

In file src/components/Bullet.tsx :
```jsx
      <span className='glyph' onClick={onClick}>
        {glyph || (showContexts ? (leaf ? '◦' : '▹') : leaf ? '•' : '▸')}               
      </span>
      <div
          className={classNames('glyph-bg', {
            expandable: !leaf, 
            active: !(publish && (isRoot || isRootChildLeaf)) && !hideBullet,
          })}
        >
          •
        </div>
```
## Notes
I have implemented this solution. The fix is in progress and it might have created regressions. 
Do you want to checkout the branch or want me to make a PR?

**Comment by raineorshine** [comment] 2022-01-31 12:15
Yes, please create a draft PR! Thanks!

**Comment by raineorshine** [comment] 2022-01-31 12:28
> 1. The css rules are extremely difficult to keep track. There are about 61 references of `.bullet-cursor-overlay` in `App.css` most of which involve rules setting top, left, margin, etc.

There are [six basic rulesets](https://github.com/cybersemics/em/blob/dev/src/App.css#L1537-L1575) for `.bullet-cursor-overlay`. The rest are overrides for android, which will likely still be needed since android renders the utf-8 character slightly differently. Perhaps they can be simplified though.

**Closed** 2022-03-12 11:59 UTC
Labels: bug, good-first-issue
