### ISSUE TITLE
Mobile incorrectly enters editing mode after drag

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#821] opened 2020-07-31 03:50 UTC
Tested in Safari, iPhone 11

## Steps to Reproduce

- a
  - b
  - c

1. Enter editing mode on `c`
2. Drag `c` above `b`
3. Close the keyboard 
4. Activate `cursorBack` (swipe right)

## Current Behavior

After Step 2, the caret disappears. The keyboard stays up on iOS and is closed on Android.

After Step 4, the keyboard comes up and [editing mode](https://github.com/cybersemics/em/wiki/Technical-Overview#9-mobile-editing-mode) is activated. 

## Expected Behavior

The caret should not disappear and the keyboard should not be closed automatically on drag.

Editing mode should stay disabled after closing the keyboard manually.

**Comment by pushkov-fedor** [comment] 2020-08-28 11:29
Tested in Android, the same current behavior. Also we have the same behavior even without dragging. I would like to pick it, 3hrs

**Comment by pushkov-fedor** [comment] 2020-09-01 10:17
@raineorshine Raine, hi! I would like to discuss one moment. I have tested this issue on IOS and Android, and keyboard behavior on each platform differs.
On IOS: it works as expected.
On Android (without dragging, just close keyboard and activate `cursorBack`):
Closing keyboard doesn't trigger blur effect. Thought input is still focused, caret is displayed, but keyboard is closed. This fact leads to `cursorBack` invocation with `editing` true, that's why keyboard expands.
On Android (with dragging):
After dragging keyboard closes automatically and caret disappears, swipe right leads to `cursorBack` execution with `editing` true, keyboard expands

Do you have the same IOS behavior, and what do you think about Android?

**Comment by raineorshine** [comment] 2020-09-01 13:45
> On IOS: it works as expected.

To clarify, iOS is not working as expected on my end. Do you mean that iOS is currently broken as described, or that on your version of iOS you cannot reproduce?

> On Android (without dragging, just close keyboard and activate `cursorBack`)

I don't notice any issues without dragging on iOS.

> On Android (with dragging):
> After dragging keyboard closes automatically and caret disappears, swipe right leads to `cursorBack` execution with `editing` true, keyboard expands

Yes, that's right. Android apparently closes the keyboard automatically, but the outcome is the same: `editing` not set to `false` on blur.

**Comment by pushkov-fedor** [comment] 2020-09-03 12:12
> > On IOS: it works as expected.
> 
> To clarify, iOS is not working as expected on my end. Do you mean that iOS is currently broken as described, or that on your version of iOS you cannot reproduce?

Cannot reproduce
![ezgif-7-9a98a40d2809](https://user-images.githubusercontent.com/32064251/92113050-f0838b80-ee18-11ea-94dd-39925f554690.gif)

**Comment by raineorshine** [comment] 2020-09-03 12:50
Maybe the Android fix will also fix iOS. Would you like to try?

**Comment by pushkov-fedor** [comment] 2020-09-04 08:16
> Maybe the Android fix will also fix iOS. Would you like to try?

Let's try!

**Closed** 2020-09-23 14:43 UTC
Labels: bug
