### ISSUE TITLE
importText: Duplicate Thought

### ISSUE THREAD

**Issue by onurpolattimur** [cybersemics/em#1196] opened 2021-05-29 19:39 UTC
I think it is a regression from 354c6f32b.

## Steps to Reproduce

``` 
- a
- a
``` 

Copy and paste the above text.

## Current Behavior

- a
- a

## Expected Behavior

- a

**Comment by raineorshine** [comment] 2021-05-30 13:20
Thanks @onurpolattimur!

@shresthabijay Could you take a look?

**Comment by raineorshine** [comment] 2021-05-30 13:23
While you're at it, can you check the child use case? I'm not sure what the behavior was before 354c6f3. If it doesn't work as expected, you may address it in this issue or as a separate issue.

**Input:**

```
- a
  - b
- a
  - c
``` 

**Imported:**

```
- a
  - b
  - c
```

**Comment by shresthabijay** [comment] 2021-05-31 08:59
> Thanks @onurpolattimur!
> 
> @shresthabijay Could you take a look?

Sure.

**Comment by shresthabijay** [comment] 2021-05-31 09:00
> While you're at it, can you check the child use case? I'm not sure what the behavior was before [354c6f3](https://github.com/cybersemics/em/commit/354c6f32b2ea0ad02c480b36a881c88a5436f2b2). If it doesn't work as expected, you may address it in this issue or as a separate issue.
Sure. I will take a look.

**Comment by shresthabijay** [comment] 2021-05-31 13:16
@raineorshine We removed the `collapseContext` when importing the destination context is empty in #1171. But the original intention of using `collapseContext` was to remove handles duplicates and merging children for imported thoughts. We decided to remove `collapseContext` because it helped maintain rank starting from 0 to prevent current tests from failing. I think we need to rever that specific change and update tests to use relative order instead of absolute.

**Comment by raineorshine** [comment] 2021-05-31 13:21
We imported everything into an isolated dummy thought in order to prevent conflicts with existing thoughts. I don't think that addresses the case where the imported text itself contains duplicate siblings. That would have unexpected behavior even before `collapseContext` was called, right?

**Comment by shresthabijay** [comment] 2021-05-31 14:37
> We imported everything into an isolated dummy thought in order to prevent conflicts with existing thoughts. I don't think that addresses the case where the imported text itself contains duplicate siblings. That would have unexpected behavior even before `collapseContext` was called, right?

Yes. `imported` already has duplicate thoughts, but since `collapseContext` context copies thought one by one using `exisitingThoughtChange`, it actually handles all the duplication and merging logic.

**Comment by raineorshine** [comment] 2021-05-31 15:01
> `imported` already has duplicate thoughts, but since `collapseContext` context copies thought one by one using `exisitingThoughtChange`, it actually handles all the duplication and merging logic.

What if the duplicates are deeper? `collapseContext` only individually moves direct children.

- a
  - b
    - c
      - d
    - c
      - e

> it actually handles all the duplication and merging logic. I think that was the original intention to use `collapseContext` in `importText`.

The original intention was to handle conflicts between existing thoughts and imported thoughts. We hadn't considered duplicate siblings in the imported content. See #993 for original problem statement and discussion that led to `collapseContext` being added to `importText` in #1025.

**Comment by shresthabijay** [comment] 2021-05-31 15:12
> The original intention was to handle conflicts between existing thoughts and imported thoughts. We hadn't considered duplicate siblings in the imported content. See #993 for original problem statement and discussion that led to `collapseContext` being added to `importText` in #1025.

Got it! So we should handle duplicates and merging in the `importedText` before updating the thoughts.

**Comment by raineorshine** [comment] 2021-05-31 15:29
Yes, but let's assess the effort involved before diving into an implementation. This could get hairy. For example, multiple levels of duplicates does not import well at all right now:

```
- a
  - b
    - c
    - d
- a
  - b
    - d
    - e
```

The last thing we want is to re-implement conflict and merge logic that is already implemented in `existingThoughtMove`.

We may want to consider avoiding duplication completely in the initial import by incrementing duplicates. This imports without issues:

```
- a
  - b
    - c
    - d
- a(1)
  - b
    - d
    - e
```

After this step we could theoretically indent each duplicate into a dummy and collapse the dummy in order to utilize the existing merge logic. It would need to be done recursively.

It assumes the user actually wants them merged. Presumably they were separate in the source for a reason. It's probably best to not merge them at all, and just take steps as described above to prevent duplicate siblings. Then the user can merge them manually if they want to. 

This changes the desired behavior described in the original issue, but it seems easier to implement and more conservative with the user's thoughts. What do you think?

**Comment by shresthabijay** [comment] 2021-05-31 15:45
> This changes the desired behavior described in the original issue, but it seems easier to implement and more conservative with the user's thoughts. What do you think?

I love this approach. A user would be able to see duplicates themselves and can do what they wish with them.

**Closed** 2021-06-02 13:48 UTC
Labels: bug
