### ISSUE TITLE
Cursor not set properly after blur

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#674] opened 2020-05-19 14:47 UTC
## Steps to Reproduce

1. Create a thought with some text
2. Close the keyboard (mobile) or blur the selection by switching to another window (desktop)
3. Click on the thought

## Current Behavior

Cursor disappears. 

## Expected Behavior

Cursor should not change.

**Comment by shresthabijay** [comment] 2020-05-21 15:32
@raineorshine I couldn't recreate this issue in desktop. It only happens in mobile. After blur, tapping again sets the cursor but it doesn't have selection on the input. 

https://github.com/cybersemics/em/blob/c8688c4e7bfa403580d4a28def74e36a7fa67a4e/src/components/Editable.js#L212-L214  

As you can see in this side-effect, unless `editing` is true `setSelection` won't execute for mobile. Shouldn't a thought execute `setSelection` when it has `isEditing` true ?

**Comment by raineorshine** [comment] 2020-05-21 22:27
These variables are confusing. We should probably rename `editing` → `editingMode`.

- `isEditing` - `true` if the cursor is on the thought
- `editing` - `true` if the keyboard is up on mobile

The quoted condition correctly calls `setSelection` when `isEditing` is true, as long as the keyboard is open on mobile (`!isMobile || editing`). When the keyboard is closed, the editable should not be focused on load.

The problem is that `isEditing` is incorrectly set to `false` when the thought is re-focused:

https://github.com/cybersemics/em/blob/dev/src/components/Thought.js#L104-L105

In this case (after editing the thought), `thoughtsResolved` seems to be updated to the live value, even before `cursorBeforeEdit` is updated. `cursorBeforeEdit` should not be updated until the cursor has moved. Thus I would expect that the pre-edit value would be compared in order to set `isEditing` to true.

The regression occurred at 17189bc387b17a862f1acf21e983b5f6dadc9ad4. It works in the previous commit, 41a0ebb9f36c876f08cf5c8ec06810fa232efc94. However when I try to revert the addition of `cursorBeforeEdit: state.cursor` on `dev`, it doesn't seem to fix it, so there must be another commit that is also contributing to the problem. I went through these steps twice, but I recommend doing it yourself to confirm, as it's a bit tricky.

Note that you can recreate the issue on desktop by editing the thought, clicking into the Javascript console to blur it, and then clicking back on the thought.

**Comment by shresthabijay** [comment] 2020-05-22 06:51
I am little confused here. I wanna clear some doubts. In mobile when a user taps outside a thought after editing, the cursor is set to null. After that when he taps the thought it just sets the cursor on thought without selection. After that tapping once again sets the cursor selection to the thought. I believe this is to allow user to navigate without bringing up keyboard every time.

Here is what happens when I try to recreate the issue on mobile. I edited a thought and then blurred by closing keyboard and then tapped on the thought again. 

https://drive.google.com/file/d/1PS1TGw7u6zA1JfH4KUvySUu475hc-cYe/view?usp=sharing

As you see cursor is set to the thought but selection doesn't happen right away. It only happens if I tap it again. Is this the issue or am I getting it wrong ?

**Comment by raineorshine** [comment] 2020-05-22 13:34
> I am little confused here. I wanna clear some doubts. In mobile when a user taps outside a thought after editing, the cursor is set to null. After that when he taps the thought it just sets the cursor on thought without selection. After that tapping once again sets the cursor selection to the thought. I believe this is to allow user to navigate without bringing up keyboard every time.

Yes, that is correct. (Technically, when the user taps outside a thought, it calls `cursorBack`, which will set the `cursor` to `null` if the `cursor` was at the root.)

> Here is what happens when I try to recreate the issue on mobile. I edited a thought and then blurred by closing keyboard and then tapped on the thought again.
> 
> [drive.google.com/file/d/1PS1TGw7u6zA1JfH4KUvySUu475hc-cYe/view?usp=sharing](https://drive.google.com/file/d/1PS1TGw7u6zA1JfH4KUvySUu475hc-cYe/view?usp=sharing)
> 
> As you see cursor is set to the thought but selection doesn't happen right away. It only happens if I tap it again. Is this the issue or am I getting it wrong ?

The issue is not occurring on your mobile device from what I can tell. What happens for me is that the `cursor` disappears completely when I click on the thought after closing the keyboard.

This is not only a mobile issue though and I recommend trying to reproduce on desktop by editing the thought, clicking into the Javascript console to blur it, and then clicking back on the thought. I can take the issue if needed if you are unable to reproduce.

**Comment by shresthabijay** [comment] 2020-05-22 15:24
> This is not only a mobile issue though and I recommend trying to reproduce on desktop by editing the thought, clicking into the Javascript console to blur it, and then clicking back on the thought. I can take the issue if needed if you are unable to reproduce.

I tried it on desktop too. I am not able to reproduce it. Could it be browser specific issue ? Which browser did you test on desktop and mobile ?

**Comment by raineorshine** [comment] 2020-05-22 17:25
> Which browser did you test on desktop and mobile ?

Desktop Chrome and Mobile Safari

**Closed** 2020-05-23 21:37 UTC
Labels: bug
